### ISSUE TITLE
Connext Video Demo has Stopped

### ISSUE THREAD

**Issue by sanwar2004** [rticommunity/rticonnextdds-videodemo-android#1]
I successfully downloaded the apk file to my android phone - Alcatel OneTouch

Icon successfully appears under apps - "Connext Video Demo"

When i launch - get message "Unfortunately, Connext Video Demo has Stopped."

**Comment by howard-rti** [comment]
Sorry, haven't tried running on that phone.  It's possible that your hardware doesn't support the underlying gstreamer libraries...  Have you been able to try on a different phone/tablet?
