### ISSUE TITLE
Streaming doesn't work

### ISSUE THREAD

**Issue by sbrcina** [rticommunity/rticonnextdds-videodemo-android#2]
Hi, 

I am trying to compile and build your code. Finally build it, but now I am getting some error messages on the phone who is subscriber.
It looks like this:

0:03:32.376481185 0x58fd53b0 gstcapsfilter.c:456:gst_capsfilter_prepare_buf:<capsfilter4> error: Filter caps do not completely specify the output format

0:03:32.376567560 0x58fd53b0 gstcapsfilter.c:456:gst_capsfilter_prepare_buf:<capsfilter4> error: Output caps are unfixed: video/x-vp8, width=(int)[ 1, 2147483647 ], height=(int)[ 1, 2147483647 ], framerate=(fraction)[ 0/1, 2147483647/1 ]

0:03:32.376780268 0x58fd53b0 gstbasetransform.c:2207:default_generate_output:<capsfilter4> could not get buffer from pool: error

0:03:32.376912768 0x58fd53b0 gstbasesrc.c:2943:gst_base_src_loop:<src> error: Internal data flow error.

0:03:32.376984435 0x58fd53b0 gstbasesrc.c:2943:gst_base_src_loop:<src> error: streaming task paused, reason error (-5)

Do you know what can be the issue?

**Comment by howard-rti** [comment]
Sorry, we're not gstreamer experts.  You might wanna check on some gstreamer forums.

Did you make changes to the way that gstreamer was setup in ConnextGstreamer.cxx?

As far as I know the code that was in github was working:

for sending from Android

```
    sprintf(pipeline, "appsrc name=\"src\" is-live=\"true\" do-timestamp=\"true\" "
            " min-latency=0 max-latency=100000000 "
            " ! video/x-raw, format=NV21, width=%d, height=%d, framerate=(fraction)15/1 "
            " ! videoconvert "
            " ! vp8enc deadline=1 threads=5 keyframe-max-dist=30 buffer-size=10 buffer-initial-size=10 buffer-optimal-size=10 "
            " ! video/x-vp8, profile=(string)2 "
            " ! appsink name=\"sink\" ",
            width, height);
```

for receiving and displaying on Android.

```
sprintf(pipeline, "appsrc name=\"src\" is-live=\"true\" do-timestamp=\"true\" "
        " min-latency=0 max-latency=100000000 "
        " ! video/x-vp8 "
        " ! vp8dec threads=5 "
        " ! autovideosink name=\"sink\" ");
```
